<footer>
	<?php
	$_footer_notice = get_theme_mod('antonia_footer_notice', 'The content on this site was not generated by AI.');
	if ($_footer_notice) : ?>
		<h3><?php echo esc_html($_footer_notice); ?></h3>
	<?php endif; ?>
	<h3>
		<?php
		echo esc_html(
			sprintf(
				/* translators: 1: four-digit year, 2: site name */
				__('Copyright © %1$s %2$s. All rights reserved.', 'antonia-zanolli'),
				date('Y'),
				get_bloginfo('name')
			)
		);
		?>
	</h3>
	<h3>
		<?php
		wp_nav_menu([
			'theme_location' => 'footer',
			'container'      => 'div',
			'container_class' => 'footer-nav',
			'items_wrap'     => '%3$s',
			'walker'         => new Antonia_Plain_Walker(),
			'fallback_cb'    => false,
		]);
		?>
	</h3>
	<h3>
		<?php
		printf(
			/* translators: %s = link to developer site */
			wp_kses_post(__('Created by %s', 'antonia-zanolli')),
			'<a href="https://josephhansen.dev">Joseph Hansen</a>'
		);
		?>
	</h3>
</footer>

<?php wp_footer(); ?>
</body>

</html>