<footer>
	<h3><?php esc_html_e( 'The content on this site was not generated by AI.', 'antonia-zanolli' ); ?></h3>
	<h3>
		<?php
		echo esc_html(
			sprintf(
				/* translators: %s = current year */
				__( 'Copyright © %s Antonia Zanolli. All rights reserved.', 'antonia-zanolli' ),
				date( 'Y' )
			)
		);
		?>
	</h3>
	<h3>
		<?php
		wp_nav_menu( [
			'theme_location' => 'footer',
			'container'      => 'div',
			'container_class'=> 'footer-nav',
			'items_wrap'     => '%3$s',
			'walker'         => new Antonia_Plain_Walker(),
			'fallback_cb'    => false,
		] );
		?>
	</h3>
	<h3>
		<?php
		printf(
			/* translators: %s = link to developer site */
			wp_kses_post( __( 'Created by %s', 'antonia-zanolli' ) ),
			'<a href="https://josephhansen.dev">Joseph Hansen</a>'
		);
		?>
	</h3>
</footer>

<?php wp_footer(); ?>
</body>
</html>
